### PR TITLE
Added photo

### PR DESCRIPTION
**Pull request by AlexWalschots**
Added photo of the store Urban Outfitters to second paragraph

### CODE REVIEW

**Comment by geyerbri** [comment]
Please rename your images folder will only lowercase letters.

Second, you have not added this image to your project file. Please follow the directions on the wiki: [https://github.com/msu-anthropology/indian-country-ss18/wiki/Images-with-Captions](https://github.com/msu-anthropology/indian-country-ss18/wiki/Images-with-Captions). Use the first block of code as your example (the second block of code is a more complicated version we are not using)

**Comment by AlexWalschots** [comment]
Fixed imagine folder name and added image

**Comment by AlexWalschots** [comment]
Hello, I believe I corrected the mistakes. Hope it works now!

- Alex Walschots

________________________________

**Comment by geyerbri** [comment]
Thank you. This is turned in. When you add another image to your images folder later, its new all-lowercase name should show up correctly.

**Pull request merged**
