### PR TITLE
REPO 2 FEB 15

### PR DESCRIPTION
**Pull request by godellta**

### CODE REVIEW

**Comment by geyerbri** [comment]
For some reason your own repo doesn't yet include the actual image file you've written about in your project code, but I don't know why. Is it possible you forgot to move the image into the folder you created inside your project folder?

Confirm the image is in there. If it wasn't and you do move it in there, use the github application to Commit the image to the repo and Push the image to GitHub's cloud. If you have trouble, follow the directions on pages 5 and 6 of the wiki: [https://github.com/msu-anthropology/indian-country-ss18/wiki](https://github.com/msu-anthropology/indian-country-ss18/wiki)

**Comment by godellta** [comment]
Hey Brian, 

The image does show up in my image folder for the project and when I open it offline like you showed us, the image shows up. Is there anything I need to change possibly or do differently to make it work with the image file itself?

**Comment by geyerbri** [comment]
Ok knowing that leads me to believe it still needs to be committed and pushed. You will use the application on your computer for that. Those steps are spelled out on pages 5 and 6 of the wiki: [https://github.com/msu-anthropology/indian-country-ss18/wiki](https://github.com/msu-anthropology/indian-country-ss18/wiki)

**Comment by godellta** [comment]
I just committed and pushed the image itself. Does it appear now?

**Comment by geyerbri** [comment]
It sure does! You've finished this.

**Pull request merged**
