### PR TITLE
Formating, not done yet

### PR DESCRIPTION
**Pull request by NicholasMells**
Formating a bit to put more information in later tonight

### CODE REVIEW

**Comment by NicholasMells** [comment]
Hey brian in late anticipation i am formatting my page and putting in more information as to not be embarrassed. Best

**Comment by NicholasMells** [comment]
Testing something

**Comment by geyerbri** [comment]
I'm going to leave your request open until you either write a message saying you're done, or the morning before class. That way you don't have to worry about whether or not your work tonight has been completely included.

**Comment by NicholasMells** [comment]
Thank you so much! Is there anyway to fix the see more details section on the map before tomorrow?
Nicholas M. Mells
Michigan State University Class of 2019
Economic Geography B.S. 
Interdisciplinary Humanities B.A.
History, English Literature, American Indian & Indigenous Studies
Email: nicholasmells@yahoo.com | mellsnic@msu.edu
Phone: (313)-909-6994 

    On Tuesday, April 17, 2018, 11:14:28 PM EDT, Brian Geyer <notifications@github.com> wrote:  
 
 
I'm going to leave your request open until you either write a message saying you're done, or the morning before class. That way you don't have to worry about whether or not your work tonight has been completely included.

**Comment by geyerbri** [comment]
To fix your pin/popup, find the email from Dr. Howard with the link to the Google form, then edit your answers (it won't let you submit new answers, but edit the ones you already provided).

Make sure to closely follow the instructions written for each entry, particularly about quotations around your intro text and link, and no brackets around the intro text. 

The link is best completed by copying the full example (with the quotations) and changing the pathway to point to your own project folder/file.

**Comment by NicholasMells** [comment]
Hey brian i see where I made the mistake at and resubmitted the information! thank you so much for you patience, I will be continuing to work on the project until the morning, and I will email you when I wish to commit my last changes
Nicholas M. Mells
Native American Institute-Intern
Michigan State University Class of 2019
Economic Geography B.S. 
Interdisciplinary Humanities B.A.
History, English Literature, American Indian & Indigenous Studies
Email: nicholasmells@yahoo.com | mellsnic@msu.edu
Phone: (313)-909-6994 

    On Tuesday, April 17, 2018, 11:37:21 PM EDT, Brian Geyer <notifications@github.com> wrote:  
 
 
To fix your pin/popup, find the email from Dr. Howard with the link to the Google form, then edit your answers (it won't let you submit new answers, but edit the ones you already provided).

Make sure to closely follow the instructions written for each entry, particularly about quotations around your intro text and link, and no brackets around the intro text.

The link is best completed by copying the full example (with the quotations) and changing the pathway to point to your own project folder/file.

**Comment by geyerbri** [comment]
No need to email if you're going to work through the night.

Tomorrow morning, just after 10 am, I will accept any remaining open pull requests so that everything is up to date for class.

Just in case you weren't aware, you can check on what the class version of your page will look like by looking at what _your own_ version looks like: https://NicholasMells.github.io/indian-country-ss18/sites/alaskan-schools/alaskan-schools.html

For a final note to you before I go to bed (because I see, on your version, your images aren't showing up) image problems are often called by capitalization differences between folder/file names in your code and in your actual files.

**Pull request merged**
