### PR TITLE
Thing i did on 3/16/2018

### PR DESCRIPTION
**Pull request by NicholasMells**
I believe I uploaded my image file here

### CODE REVIEW

**Comment by geyerbri** [comment]
There are a ton of problems with the files in your project folder that need to be removed. There are other image files that do not meet the naming requirements I've shared with the class (lowercase letters and dashes instead of spaces).

You will need to make time with me to fully clean up your project's files.

**Comment by NicholasMells** [comment]
Can we meet wednesday after 12:20?
Nicholas M. Mells
Native American Institute-Intern
Michigan State University Class of 2019
Economic Geography B.S. 
Interdisciplinary Humanities B.A.
History, English Literature, American Indian & Indigenous Studies
Email: nicholasmells@yahoo.com | mellsnic@msu.edu
Phone: (313)-909-6994 

    On Saturday, March 17, 2018, 1:36:56 PM EDT, Brian Geyer <notifications@github.com> wrote:  
 
 
There are a ton of problems with the files in your project folder that need to be removed. There are other image files that do not meet the naming requirements I've shared with the class (lowercase letters and dashes instead of spaces).

You will need to make time with me to fully clean up your project's files.

**Comment by geyerbri** [comment]
Please email me directly so we can schedule something, since this platform is technically open to the public.

**Comment by geyerbri** [comment]
Thank you for taking care of the extra files.

I am waiting until after midnight to make the final marks for who has completed and who hasn't. You still need to add an image to your project's html file. If you remember, I pointed you to the wiki page related to adding images with captions. https://github.com/msu-anthropology/indian-country-ss18/wiki/Images-with-Captions

Please do that work (you can copy and paste the first block of code on that page and alter it for your own image and caption) so that I can mark you as complete.

**Comment by geyerbri** [comment]
There is no more work added here, but I am closing this to prepare for today's class.

**Pull request merged**
