### PR TITLE
Navajo Appropriation Assignment 1 

### PR DESCRIPTION
**Pull request by AlexWalschots**

### CODE REVIEW

**Comment by geyerbri** [comment]
I have noticed that your folder name as a space at the end. Please rename your folder to delete that space, then commit the change with the application and Push the change to the cloud. Doing that will automatically update this pull request.

**Comment by AlexWalschots** [comment]
Hello! I renamed the folder, but the only way that I was able to was through the application on my "Finder." Is that correct?

-Alex Walschots

________________________________

**Comment by geyerbri** [comment]
Yes, that is how you rename it. Now you should be able to commit the name change by opening your github application on your computer and it will be listed as a change (it actually should say you're "deleting" the file with the old folder name and "creating" the file with the new name.

Give that commit a summary and click "Commit to master." Then click "Push origin" and it should complete the process.

If your application doesn't show the name change at all, don't worry too much about it, this won't affect your grade. Just remind me the next time you are in and I'll make sure the name change goes through the system (sometimes the system doesn't recognize deleted spaces)

**Comment by geyerbri** [comment]
Great, thank you.

**Pull request merged**
